# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#0071e3"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[server]
maxUploadSize = 200
